# 1 Tensors
## 1.1 Basic Tensor Construction

### Using PyTorch

In [4]:
import torch

In [6]:
x_pt = torch.tensor(25)
x_pt

tensor(25)

In [7]:
x_pt.shape

torch.Size([])

In [32]:
x_pt = torch.tensor([25,2,5])
x_pt

tensor([25,  2,  5])

In [62]:
X_pt = torch.tensor([[25,2],[26,5],[3,7]])
X_pt

tensor([[25,  2],
        [26,  5],
        [ 3,  7]])

In [63]:
X_pt.shape

torch.Size([3, 2])

In [72]:
images_pt = torch.zeros([32,28,28,3])
images_pt;

### Using TensorFlow

In [8]:
import tensorflow as tf

In [9]:
x_tf = tf.Variable(25, dtype=tf.int16)
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>

In [10]:
x_tf.shape

TensorShape([])

In [15]:
y_tf = tf.Variable(3, dtype=tf.int16)
y_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=3>

In [16]:
tf_sum = tf.add(x_tf,y_tf)
tf_sum

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [17]:
tf_sum.numpy()

28

In [33]:
x_tf = tf.Variable([25,2,5])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5])>

In [65]:
X_tf = tf.Variable([[25,2],[26,5],[3,7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [26,  5],
       [ 3,  7]])>

In [66]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [67]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2])>

In [68]:
X_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([26,  5])>

In [73]:
images_tf = tf.zeros([32,28,28,3])
images_tf;

### Using Numpy

In [46]:
import numpy as np

In [47]:
x = np.array([25,2,5])

In [48]:
len(x)

3

In [49]:
x.shape

(3,)

In [50]:
type(x)

numpy.ndarray

In [51]:
type(x[0])

numpy.int32

#### Vector Transposition

In [52]:
x_t = x.T
x_t

# No effects because x is a 1-D array (it has only 1 axis)

array([25,  2,  5])

In [53]:
y = np.array([[25,2,5]])
y

array([[25,  2,  5]])

In [54]:
y.shape

(1, 3)

In [55]:
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [56]:
y_t.shape

(3, 1)

#### Norms

In [57]:
#L2 norm
print(x)
print(np.linalg.norm(x))

[25  2  5]
25.573423705088842


In [58]:
#L1 norm (sum of absolute values)
l1 = np.abs(x[0])+np.abs(x[1])+np.abs(x[2])
l1

32

In [59]:
#L2 squared norm (basically dot produto)
np.dot(x,x)

654

In [60]:
#Lmax (max norm) simply gets the max of all absolute values
x_abs = []
for x in x:
    x_abs.append(np.abs(x))
np.max(x_abs)

25

#### Matrices

In [40]:
X = np.array([[25,2],[5,26],[3,7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [41]:
X.shape

(3, 2)

In [42]:
X.size

6

## 1.2 Tensor Operations

In [79]:
X = np.array([[25,2],[5,26],[3,7]])
X_tf = tf.Variable([[25,2],[26,5],[3,7]])
X_pt = torch.tensor([[25,2],[26,5],[3,7]])

Y = np.array([[35,2],[5,36],[2,7]])
Y_tf = tf.Variable([[35,2],[36,5],[2,7]])
Y_pt = torch.tensor([[35,2],[36,5],[2,7]])

In [78]:
# Transpose
print(
X.T,  
X_pt.T,
tf.transpose(X_tf),sep='\n\n')

[[25  5  3]
 [ 2 26  7]]

tensor([[25, 26,  3],
        [ 2,  5,  7]])

tf.Tensor(
[[25 26  3]
 [ 2  5  7]], shape=(2, 3), dtype=int32)


In [80]:
# Scalar and Addition
print(
X*2+2,  
X_pt*2+2,
tf.add(tf.multiply(X_tf,2),2),sep='\n\n')

[[52  6]
 [12 54]
 [ 8 16]]

tensor([[52,  6],
        [54, 12],
        [ 8, 16]])

tf.Tensor(
[[52  6]
 [54 12]
 [ 8 16]], shape=(3, 2), dtype=int32)


In [85]:
# Element-wise operations (addition)
print(
X+Y,
X_pt+Y_pt,
X_tf+Y_tf,sep='\n\n')

[[60  4]
 [10 62]
 [ 5 14]]

tensor([[60,  4],
        [62, 10],
        [ 5, 14]])

tf.Tensor(
[[60  4]
 [62 10]
 [ 5 14]], shape=(3, 2), dtype=int32)


In [86]:
# Element-wise operations (multiplication)
print(
X*Y,
X_pt*Y_pt,
X_tf*Y_tf,sep='\n\n')

[[875   4]
 [ 25 936]
 [  6  49]]

tensor([[875,   4],
        [936,  25],
        [  6,  49]])

tf.Tensor(
[[875   4]
 [936  25]
 [  6  49]], shape=(3, 2), dtype=int32)


- Dot Product

In [88]:
x = np.array([1,2,3])
y = np.array([4,5,6])
x_y = np.dot(x,y)
x_y

32

#### Matrix Multiplication

In [97]:
X = np.array([[25,2,3],[5,26,4],[3,7,5]])
y = np.array([1,2,3])

In [98]:
np.dot(X,y)

array([38, 69, 32])

In [99]:
np.dot(X,X)

array([[644, 123,  98],
       [267, 714, 139],
       [125, 223,  62]])

# 2 Singular Value Decomposition (SVD)
- A = UDV(t)

In [100]:
X = np.array([[-1,2],[3,-2],[5,7]])

In [102]:
U, d, VT = np.linalg.svd(X)

In [103]:
U

array([[ 0.12708324,  0.47409506,  0.87125411],
       [ 0.00164602, -0.87847553,  0.47778451],
       [ 0.99189069, -0.0592843 , -0.11241989]])

In [111]:
d
np.diag(d)
D = np.concatenate((np.diag(d),[[0,0]]),axis=0)
D

array([[8.66918448, 0.        ],
       [0.        , 4.10429538],
       [0.        , 0.        ]])

In [105]:
VT

array([[ 0.55798885,  0.82984845],
       [-0.82984845,  0.55798885]])

In [112]:
np.dot(U,np.dot(D,VT))

array([[-1.,  2.],
       [ 3., -2.],
       [ 5.,  7.]])