## Por: victordhn
- Fiz todas anotações em inglês porque é mais fácil de acompanhar.
- Os próximos notebooks vou tentar escrever as anotações em Português.
#### Seguindo tutorial do @keithgalli

# Numpy training

In [2]:
import numpy as np
import sys

## Basics

In [16]:
a = np.array([[1,2,3],[1.1,2.1,3.1]])
print(a)

print("Dimension =",a.ndim) #a.ndim = dimension
print("Shape =",a.shape) #a.shape = shape

[[1.  2.  3. ]
 [1.1 2.1 3.1]]
Dimension = 2
Shape = (2, 3)


## Types 

### Important info for me here:
Using numpy, setting the type to string will get only 1 character of the text. I don't want to go into details here, but you should use dtype='U10' or dtype='<U50' or whatever string size you want instead of using dtype=str

In [44]:
### simple types
print("Simple Types:")
x = np.array([1,2,3])
y = np.array(["one","two","three"])
z = np.array([1.1,2.2,3.3])
print("Type x =",x.dtype)
print("Type y =",y.dtype)
print("Type z =",z.dtype)

print("\nType prevalence (str>float>int>bool):")
### type prevalence: str>float>int>bool
i = np.array([1,1.2,"one",True])
print("Type i =",i.dtype)
j = np.array([1,1.2,True])
print("Type j =",j.dtype)
k = np.array([1,True])
print("Type k =",k.dtype)
l = np.array([True])
print("Type l =",l.dtype)

print("\nType setting:")
### type setting
r = np.array([1,3.2],dtype=int)
print("Type r =",r.dtype)


Simple Types:
Type x = int32
Type y = <U5
Type z = float64

Type prevalence (str>float>int>bool):
Type i = <U32
Type j = float64
Type k = int32
Type l = bool

Type setting:
Type r = int32


## Indexing and manipulating values

In [70]:
a = np.array([[0,1,2,3,4,5,6,7],[8,9,10,11,12,13,14,15]])
print(a)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [52]:
# get specific element [r,c]
print(f"My birthday is on day a[0,3]a[0,0] = {a[0,3]}{a[0,0]}")

My birthday is on day a[0,3]a[0,0] = 30


In [54]:
# get rows and columns
print("Row 1 =",a[0,:])
print("Column 1 =",a[:,0])

Row 1 = [0 1 2 3 4 5 6 7]
Column 1 = [0 8]


In [62]:
# using intervals and stepsize [startindex:endindex:stepsize]
print("First row =",a[0,:])
print("First row, from index 1 to 6 (including 6), get one jump one =",a[0,1:7:2])
print("Inverse order: start at index -3 and go backwards =",a[0,-3:-9:-2])

First row = [0 1 2 3 4 5 6 7]
First row, from index 1 to 6 (including 6), get one jump one = [1 3 5]
Inverse order: start at index -3 and go backwards = [5 3 1]


In [73]:
# change a value
print("First row =",a[0,:]) 
a[0,0]=100
print("First element is 100 =",a[0,:])
a[0,0]=0

print("First column =",a[:,0])
a[:,0]=[100,200]
print("First column is [100,200] =\n",a[:,:])
a[:,0]=[0,8]

First row = [0 1 2 3 4 5 6 7]
First element is 100 = [100   1   2   3   4   5   6   7]
First column = [0 8]
First column is [100,200] =
 [[100   1   2   3   4   5   6   7]
 [200   9  10  11  12  13  14  15]]


In [83]:
# 3-d matrix
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
print("\nElement from page 1, row 2, column 1 =",b[0,1,0])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Element from page 1, row 2, column 1 = 3


## Initializing types of arrays
- zeros
- ones
- rand (decimals 0-1)
- randint (integers)
- identity

In [89]:
#all 0's matrix
zeros_row = np.zeros(5)
zeros_23 = np.zeros((2,3))
zeros_233 = np.zeros((2,3,3))

print("Row of zeros =",zeros_row)
print("2x3 zeros =\n",zeros_23)
print("2x3x3 zeros =\n",zeros_233)

Row of zeros = [0. 0. 0. 0. 0.]
2x3 zeros =
 [[0. 0. 0.]
 [0. 0. 0.]]
2x3x3 zeros =
 [[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [106]:
#all 1's matrix
ones_row = np.ones(5)
ones_23 = np.ones((2,3))
ones_233 = np.ones((2,3,3))

print("Row of ones =",ones_row)
print("2x3 ones =\n",ones_23)
print("2x3x3 ones =\n",ones_233)

Row of ones = [1. 1. 1. 1. 1.]
2x3 ones =
 [[1. 1. 1.]
 [1. 1. 1.]]
2x3x3 ones =
 [[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [110]:
#all any value's matrix
full_233 = np.full((2,3,3),"victor")
print("2x3x3 victor =\n",full_233)

#using the shape of another matrix as reference
print("\noriginal 2x3 of zeros =\n",zeros_23)
ref_full = np.full_like(zeros_23,"2x3",dtype='<U10')
print("\nfull like using 2x3 reference =\n",ref_full)

2x3x3 victor =
 [[['victor' 'victor' 'victor']
  ['victor' 'victor' 'victor']
  ['victor' 'victor' 'victor']]

 [['victor' 'victor' 'victor']
  ['victor' 'victor' 'victor']
  ['victor' 'victor' 'victor']]]

original 2x3 of zeros =
 [[0. 0. 0.]
 [0. 0. 0.]]

full like using 2x3 reference =
 [['2x3' '2x3' '2x3']
 ['2x3' '2x3' '2x3']]


In [123]:
#generate a matrix of random decimal numbers
random = np.random.rand(3,3)
print("Random matrix 3x3 =\n",random)
print("\nImportant note: here we pass the shape directly, and not on a tupple like the zeros, ones, and full matrices")

#using the same shape of another matrix
random_ref = np.random.random_sample(zeros_23.shape)
print("\nRandom matrix using other 2x3 matrix's shape =\n",random_ref)

Random matrix 3x3 =
 [[0.72042776 0.61359597 0.22198302]
 [0.29407091 0.88997301 0.75019121]
 [0.36808467 0.86692356 0.97299561]]

Important note: here we pass the shape directly, and not on a tupple like the zeros, ones, and full matrices

Random matrix using other 2x3 matrix's shape =
 [[0.99622342 0.05769758 0.25628883]
 [0.21760044 0.54814586 0.41291255]]


In [133]:
#random integers
#between 5 and 10, for instance
random_int = np.random.randint(5,10, size=(3,3))
print("Random matrix 3x3 of integers between 5 and 10 =\n",random_int)

Random matrix 3x3 of integers between 5 and 10 =
 [[6 8 9]
 [5 9 6]
 [6 6 5]]


In [135]:
#identity matrix
id_3 = np.identity(3)
print("Identity 3x3 matrix =\n",id_3)

Identity 3x3 matrix =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [137]:
#repeating arrays
arr = np.array([[1,2,3]]) #arr = a line on a matrix
repeat_rows = np.repeat(arr,3,axis=0)
repeat_column = np.repeat(arr,3,axis=1)
print("Repeated arrays as rows =\n",repeat_rows)
print("Repeated arrays as columns =\n",repeat_column)

Repeated arrays as rows =
 [[1 2 3]
 [1 2 3]
 [1 2 3]]
Repeated arrays as columns =
 [[1 1 1 2 2 2 3 3 3]]


### Important note on copying arrays 
#### Similar to lists, typing b=a will point 'b' to the same reference of 'a', therefore, changing 'b' will change 'a' too.
Think about it in this way: you order a full 8 slice pizza and call it a mozzarella pizza, but your friend calls it a cheese pizza. If you go and eat a slice, when you friend goes and check his "cheese pizza" there will be only 7 slices, and if he eats one of those, your "mozzarella pizza" will have only 6 slices left. The thing here is that you both gave different names to the same object. The same happens with numpy arrays
#### Solution: use .copy() method to create a full copy of an array: b=a.copy()

In [165]:
a = np.array([1,2])
print("Array a =",a)
b = a
print("Array b =",b)
print("Changing first index of b")
b[0] = 3
print("Array b =",b)
print("Array a also changed =",a)
c = a.copy()
print("Now c is a hardcopy of a using .copy() method")
print("Array c =",c)
print("Changing first index of c")
c[0] = 9
print("Array c =",c)
print("Array a DO NOT change =",a)

Array a = [1 2]
Array b = [1 2]
Changing first index of b
Array b = [3 2]
Array a also changed = [3 2]
Now c is a hardcopy of a using .copy() method
Array c = [3 2]
Changing first index of c
Array c = [9 2]
Array a DO NOT change = [3 2]


## Basic Mathematics 

In [167]:
a = np.array([1,2,3,4])

In [172]:
# element wise operations
aplus = a + 2
aminus = a - 2
amult = a *  2
adiv = a / 2
apower = a ** 2
asin = np.sin(a)
print(aplus,aminus,amult,adiv,apower,asin,sep="\n")

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [171]:
b = np.array([1,0,1,0])
c = a+b
print(c)

[2 2 4 4]


## Linear Algebra
- Link with all numpy linear algebra functions: https://numpy.org/doc/stable/reference/routines.linalg.html
- There are so many good stuff like solving Ax=b, finding eigen vectors and values... 'life made easy' stuff

In [184]:
# Matrix Multiplication
a = np.ones((2,3))
b = np.full((3,2),2)
print(a,b,sep="\n")

c = np.matmul(a,b)
print("\nAxB = C =\n",c)

#new way to do matrix multiplication
d = a@b
print("\nAxB = D =\n",c)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]

AxB = C =
 [[6. 6.]
 [6. 6.]]

AxB = D =
 [[6. 6.]
 [6. 6.]]


In [182]:
# get Determinant of a matrix
iden = np.identity(3)
det_i = np.linalg.det(iden)
print(det_i)

1.0


 ## Statistics
