# Numpy training

In [2]:
import numpy as np
import sys

## Basics

In [16]:
a = np.array([[1,2,3],[1.1,2.1,3.1]])
print(a)

print("Dimension =",a.ndim) #a.ndim = dimension
print("Shape =",a.shape) #a.shape = shape

[[1.  2.  3. ]
 [1.1 2.1 3.1]]
Dimension = 2
Shape = (2, 3)


## Types 

In [44]:
### simple types
print("Simple Types:")
x = np.array([1,2,3])
y = np.array(["one","two","three"])
z = np.array([1.1,2.2,3.3])
print("Type x =",x.dtype)
print("Type y =",y.dtype)
print("Type z =",z.dtype)

print("\nType prevalence (str>float>int>bool):")
### type prevalence: str>float>int>bool
i = np.array([1,1.2,"one",True])
print("Type i =",i.dtype)
j = np.array([1,1.2,True])
print("Type j =",j.dtype)
k = np.array([1,True])
print("Type k =",k.dtype)
l = np.array([True])
print("Type l =",l.dtype)

print("\nType setting:")
### type setting
r = np.array([1,3.2],dtype=int)
print("Type r =",r.dtype)


Simple Types:
Type x = int32
Type y = <U5
Type z = float64

Type prevalence (str>float>int>bool):
Type i = <U32
Type j = float64
Type k = int32
Type l = bool

Type setting:
Type r = int32


## Indexing and manipulating values

In [70]:
a = np.array([[0,1,2,3,4,5,6,7],[8,9,10,11,12,13,14,15]])
print(a)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [52]:
# get specific element [r,c]
print(f"My birthday is on day a[0,3]a[0,0] = {a[0,3]}{a[0,0]}")

My birthday is on day a[0,3]a[0,0] = 30


In [54]:
# get rows and columns
print("Row 1 =",a[0,:])
print("Column 1 =",a[:,0])

Row 1 = [0 1 2 3 4 5 6 7]
Column 1 = [0 8]


In [62]:
# using intervals and stepsize [startindex:endindex:stepsize]
print("First row =",a[0,:])
print("First row, from index 1 to 6 (including 6), get one jump one =",a[0,1:7:2])
print("Inverse order: start at index -3 and go backwards =",a[0,-3:-9:-2])

First row = [0 1 2 3 4 5 6 7]
First row, from index 1 to 6 (including 6), get one jump one = [1 3 5]
Inverse order: start at index -3 and go backwards = [5 3 1]


In [73]:
# change a value
print("First row =",a[0,:]) 
a[0,0]=100
print("First element is 100 =",a[0,:])
a[0,0]=0

print("First column =",a[:,0])
a[:,0]=[100,200]
print("First column is [100,200] =\n",a[:,:])
a[:,0]=[0,8]

First row = [0 1 2 3 4 5 6 7]
First element is 100 = [100   1   2   3   4   5   6   7]
First column = [0 8]
First column is [100,200] =
 [[100   1   2   3   4   5   6   7]
 [200   9  10  11  12  13  14  15]]


In [81]:
# 3-d matrix
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
print("\nElement from page 1, row 2, column 1 =",b[0,1,0])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Element from page 1, row 2, column 1 = 3


## Initializing types of arrays